name: Thunder Exchange Fuel
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: Exchange
        address: 0x5f1c2c8f0c3f2e34a36f55ae4b80e594b81b33c8a41cfdf450d35bf51211ccc5
        abi_file_path: ./abis/thunder_exchange-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: OrderPlaced
          - name: OrderUpdated
          - name: OrderExecuted
          - name: OrderCanceled
