name: Thunder Exchange Fuel
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: Exchange
        address: 0x5f1c2c8f0c3f2e34a36f55ae4b80e594b81b33c8a41cfdf450d35bf51211ccc5
        abi_file_path: ./abis/thunder_exchange-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: OrderPlaced
          - name: OrderUpdated
          - name: OrderExecuted
          - name: OrderCanceled
      - name: Pool
        address: 0x6e7b503001d4f3ad0cb957d0201263c674e4cc744cece5cca587beec8422662e
        abi_file_path: ./abis/pool-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: Deposit
          - name: Withdrawal
          - name: Transfer
